backend:
  name: git-gateway
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: "dae2wp1hy"
    api_key: "161675469855318"
    default_transformations:
      - - fetch_format: auto
          quality: auto

publish_mode: simple
collections:
  - name: "groups"
    label: "Grupos da Irmandade"
    files:
      - name: "groups_file"
        label: "Grupos"
        file: "_content/groups.json"
        fields:
          - label: "Grupos"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Emblema", name: "emblem", widget: "image" }

  - name: "events"
    label: "Eventos"
    files:
      - name: "events_file"
        label: "Eventos"
        file: "_content/events.json"
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            fields:
              - { label: "Título", name: "name", widget: "string" }
              - { label: "Data", name: "date", widget: "datetime", required: false }
              - { label: "Local", name: "place", widget: "string", required: false }
              - { label: "Imagem", name: "image", widget: "image" }
              - { label: "Descrição", name: "description", widget: "text", required: false }

  - name: "galeria"
    label: "Galeria de Álbuns"
    files:
      - name: "galeria_file"
        label: "Álbuns da Galeria"
        file: "_content/galeria.json"
        fields:
          - label: "Álbuns"
            name: "albuns"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - { label: "Título do Álbum", name: "titulo", widget: "string" }
              - { label: "Descrição (opcional)", name: "descricao", widget: "text", required: false }
              - { label: "Imagem de Capa", name: "capa", widget: "image" }
              # Campo para FOTOS MÚLTIPLAS - igual ao HCP
              - label: "Fotos (múltiplas)"
                name: "fotos_multi"
                widget: "list"
                summary: "{{fields.imagem}}"
                field:
                  label: "Imagem"
                  name: "imagem"
                  widget: "image"
                  media_library:
                    config:
                      multiple: true
              # Campo para VÍDEOS - igual ao HCP
              - label: "Vídeos (links do YouTube, etc)"
                name: "videos"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "URL do Vídeo", name: "url", widget: "string" }