# Arquivo de configuração do Decap CMS

backend:
  name: git-gateway        # usando o Git Gateway do Netlify
  branch: main             # branch padrão do site
  # dica: com git-gateway não precisa de "repo:" aqui

# Biblioteca de mídia: Cloudinary (apenas API KEY, sem secret)
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: "dae2wp1hy"
    api_key: "161675469855318"
    default_transformations:
      - - fetch_format: auto
          quality: auto

media_folder: "img/uploads"     # onde o Decap salva no repositório
public_folder: "/img/uploads"   # como é servido no site

# (Opcional) Sem workflow de revisão
publish_mode: simple

collections:
  # IRMANDADE — arquivo único JSON com lista
  - name: "groups"
    label: "Grupos da Irmandade"
    files:
      - name: "groups_file"
        label: "Grupos"
        file: "_content/groups.json"
        format: "json"
        fields:
          - label: "Grupos"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Nome",   name: "name",   widget: "string" }
              - { label: "Emblema (URL ou upload)", name: "emblem", widget: "image", choose_url: true }

  # EVENTOS — arquivo único JSON com lista
  - name: "events"
    label: "Eventos"
    files:
      - name: "events_file"
        label: "Eventos"
        file: "_content/events.json"
        format: "json"
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            fields:
              - { label: "Título", name: "name", widget: "string" }
              - { label: "Data",   name: "date", widget: "string", required: false }
              - { label: "Local",  name: "place", widget: "string", required: false }
              - { label: "Imagem (URL ou upload)", name: "image", widget: "image", choose_url: true }
              - { label: "Descrição", name: "description", widget: "text", required: false }

  # GALERIA — arquivo único JSON com lista
  - name: "galeria"
    label: "Galeria"
    files:
      - name: "galeria_file"
        label: "Galeria (fotos)"
        file: "_content/galeria.json"
        format: "json"
        fields:
          - label: "Fotos"
            name: "fotos"
            widget: "list"
            field:
              label: "Imagem (URL ou upload)"
              name: "src"
              widget: "image"
              choose_url: true
