# Arquivo de configuração do Decap CMS

backend:
  name: git-gateway
  branch: main

# Configuração GLOBAL do Cloudinary (para todas as seções)
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: "dae2wp1hy"
    api_key: "161675469855318"
    default_transformations:
      - - fetch_format: auto
          quality: auto

media_folder: "img/uploads"
public_folder: "/img/uploads"
publish_mode: simple

collections:
  - name: "groups"
    label: "Grupos da Irmandade"
    files:
      - name: "groups_file"
        label: "Grupos"
        file: "_content/groups.json"
        format: "json"
        fields:
          - label: "Grupos"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Nome",   name: "name",   widget: "string" }
              - { label: "Emblema (URL ou upload)", name: "emblem", widget: "image", choose_url: true }

  - name: "events"
    label: "Eventos"
    files:
      - name: "events_file"
        label: "Eventos"
        file: "_content/events.json"
        format: "json"
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            fields:
              - { label: "Título", name: "name", widget: "string" }
              - { label: "Data",   name: "date", widget: "string", required: false }
              - { label: "Local",  name: "place", widget: "string", required: false }
              - { label: "Imagem (URL ou upload)", name: "image", widget: "image", choose_url: true }
              - { label: "Descrição", name: "description", widget: "text", required: false }

  - name: "galeria"
    label: "Galeria de Álbuns"
    files:
      - name: "galeria_file"
        label: "Álbuns da Galeria"
        file: "_content/galeria.json"
        format: "json"
        fields:
          - label: "Álbuns"
            name: "albuns"
            widget: "list"
            summary: "{{fields.titulo}}"
            fields:
              - { label: "Título do Álbum", name: "titulo", widget: "string" }
              - { label: "Descrição (opcional)", name: "descricao", widget: "text", required: false }
              - { label: "Imagem de Capa", name: "capa", widget: "image" }
              - label: "Fotos (selecione várias de uma vez)"
                name: "fotos_multi"
                widget: "list"
                summary: "{{fields.imagem}}"
                field:
                  label: "Imagem"
                  name: "imagem"
                  widget: "image"
                  # ===== CORREÇÃO APLICADA AQUI =====
                  # Repetimos a configuração para garantir que ele não se perca
                  media_library:
                    name: cloudinary
                    config:
                      multiple: true
                      cloud_name: "dae2wp1hy"
                      api_key: "161675469855318"
                  # ====================================
              - label: "Vídeos (links do YouTube, etc)"
                name: "videos"
                widget: "list"
                collapsed: true
                fields:
                  - { label: "URL do Vídeo", name: "url", widget: "string" }