# Arquivo de configuração do Decap CMS

backend:
  name: git-gateway
  repo: MarceloMserra/2.3
  branch: main

# NOVA CONFIGURAÇÃO DE MÍDIA: CLOUDINARY
media_library:
  name: cloudinary
  output_filename_only: false
  config:
    cloud_name: "dae2wp1hy"            # exatamente como no painel (sem espaços)
    api_key: "161675469855318"         # SUA API KEY (sem o secret)
    default_transformations:
      - - fetch_format: auto
          quality: auto
backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

# (Opcional) Deixe como 'simple' se não usa o fluxo de revisão
publish_mode: simple

collections:
  # IRMANDADE (um JSON com uma lista de grupos)
  - name: "groups"
    label: "Grupos da Irmandade"
    files:
      - name: "groups_file"
        label: "Grupos"
        file: "_content/groups.json"
        format: "json"
        create: true
        delete: true  
        fields:
          - label: "Grupos"
            name: "groups"
            widget: "list"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Emblema (URL ou upload)", name: "emblem", widget: "image", choose_url: true }

  # EVENTOS (um JSON com uma lista de eventos)
  - name: "events"
    label: "Eventos"
    files:
      - name: "events_file"
        label: "Eventos"
        file: "_content/events.json"
        format: "json"
        create: true
        delete: true  
        fields:
          - label: "Eventos"
            name: "events"
            widget: "list"
            fields:
              - { label: "Título", name: "name", widget: "string" }
              - { label: "Data", name: "date", widget: "string", required: false }
              - { label: "Local", name: "place", widget: "string", required: false }
              - { label: "Imagem (URL ou upload)", name: "image", widget: "image", choose_url: true }
              - { label: "Descrição", name: "description", widget: "text", required: false }

  # GALERIA (um JSON simples com lista de fotos)
  - name: "galeria"
    label: "Galeria"
    files:
      - name: "galeria_file"
        label: "Galeria (fotos)"
        file: "_content/galeria.json"
        format: "json"
        create: true
        delete: true  
        fields:
          - label: "Fotos"
            name: "fotos"
            widget: "list"
            field:
              label: "Imagem (URL ou upload)"
              name: "src"
              widget: "image"
              choose_url: true
