# Arquivo de configuração do Decap CMS

backend:
  name: git-gateway
  repo: MarceloMserra/2.3
  branch: main

# NOVA CONFIGURAÇÃO DE MÍDIA: CLOUDINARY
media_library:
  name: cloudinary
  config:
    cloud_name: dae2wpfhy
    api_key: "161675469855318"
    default_transformations:
      - - fetch_format: auto
          quality: auto

# As linhas 'media_folder' e 'public_folder' não são mais necessárias e foram removidas.

collections:
  # Coleção para os Álbuns da Galeria (Atualizada para Cloudinary)
  - name: "albums"
    label: "Álbuns da Galeria"
    folder: "_content/albums"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título do Álbum", name: "title", widget: "string" }
      - { label: "Foto de Capa", name: "cover_image", widget: "image" }
      - label: "Mídias do Álbum (permite múltiplos uploads)"
        name: "media_list"
        widget: "list"
        summary: "{{fields.media}}"
        field: { label: "Imagem ou Vídeo", name: "media", widget: "image" }
        # Habilita o upload de múltiplos arquivos de uma vez
        allow_add: true
        allow_multiple: true

  # Coleção para os Eventos (Atualizada para Cloudinary)
  - name: "events"
    label: "Eventos"
    folder: "_content/events"
    create: true
    slug: "{{fields.name}}"
    identifier_field: name
    fields:
      - { label: "Nome do Evento", name: "name", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Local (Cidade/UF)", name: "location", widget: "string" }
      - { label: "Imagem Principal", name: "image", widget: "image" }
      - { label: "Descrição Completa", name: "description", widget: "markdown" }

  # Coleção para os Brasões da Irmandade (Atualizada para Cloudinary)
  - name: "groups"
    label: "Grupos da Irmandade"
    folder: "_content/groups"
    create: true
    slug: "{{fields.name}}"
    identifier_field: name
    fields:
      - { label: "Nome do Grupo", name: "name", widget: "string" }
      - { label: "Imagem do Brasão", name: "emblem", widget: "image" }